PRODUCT_PACKAGES += \
    AccentLight-Amber \
    AccentDark-Amber \
    AccentLight-BlueLight \
    AccentDark-BlueLight \
    AccentLight-Carnation \
    AccentDark-Carnation \
    AccentLight-Cyan \
    AccentDark-Cyan \
    AccentLight-Denim \
    AccentDark-Denim \
    AccentLight-Gold \
    AccentDark-Gold \
    AccentLight-GreenLight \
    AccentDark-GreenLight \
    AccentLight-Grey \
    AccentDark-Grey \
    AccentLight-Indigo \
    AccentDark-Indigo \
    AccentLight-Lava \
    AccentDark-Lava \
    AccentLight-Lime \
    AccentDark-Lime \
    AccentLight-Orange \
    AccentDark-Orange \
    AccentLight-Oxygen \
    AccentDark-Oxygen \
    AccentLight-Pink \
    AccentDark-Pink \
    AccentLight-Pixel \
    AccentDark-Pixel \
    AccentLight-Purple \
    AccentDark-Purple \
    AccentLight-Red \
    AccentDark-Red \
    AccentLight-Teal \
    AccentDark-Teal \
    AccentLight-Turquoise \
    AccentDark-Turquoise \
    AccentLight-Yellow \
    AccentDark-Yellow \
    AccentLight-Black \
    AccentDark-White \
