PRODUCT_PACKAGES += \
    Accent-Amber \
    Accent-BlueLight \
    Accent-Carnation \
    Accent-Cyan \
    Accent-Denim \
    Accent-Gold \
    Accent-GreenLight \
    Accent-Grey \
    Accent-Indigo \
    Accent-Lava \
    Accent-Lime \
    Accent-Orange \
    Accent-Oxygen \
    Accent-Pink \
    Accent-Pixel \
    Accent-Purple \
    Accent-Red \
    Accent-Teal \
    Accent-Turquoise \
    Accent-WhiteBlack \
    Accent-Yellow \
