PRODUCT_PACKAGES += \
    DefaultDark-System \
    DefaultDark-SystemUI \
    DefaultDark-Calculator \
    DefaultDark-Contacts \
    DefaultDark-DeskClock \
    DefaultDark-Dialer \
    DefaultDark-DocumentsUI \
    DefaultDark-Messaging \
    DefaultDark-PackageInstaller \
    DefaultDark-Phone \
    DefaultDark-Telecom \
    DefaultDark-SettingsIntelligence \
    DefaultDark-Settings \
    DefaultBlack-System \
    DefaultBlack-SystemUI \
    DefaultDarkNotif-System \
    DefaultDarkNotif-SystemUI \
    DefaultBlackNotif-System \
    DefaultBlackNotif-SystemUI \
    DefaultDarkTransparent-System \
    DefaultDarkTransparent-SystemUI \
    DefaultBlackTransparent-System \
    DefaultBlackTransparent-SystemUI \
